version: "3.9"
services:
    node:
        tty: true
        build: .
        ports:
            - '8080:8080'
        volumes:
            - ../NodeAPI:/usr/src/app
            - /usr/src/app/node_modules