version: "3.9"
services:
    node:
        tty: true
        build: .
        ports:
            - '4200:4200'
        volumes:
            - ../Angular:/usr/src/app
            - /usr/src/app/node_modules